# Site settings
title: ErikJhordan_Rey
description: A blog about Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erikcaffrey.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Erik Jhordan Rey 1
user_description: Mobile Engineer at Schibsted-Segundamano
user_title: Mobile Engineer
email: erikcaffrey10@gmail.com
twitter_username: ErikJhordan_Rey
github_username:  erikcaffrey
gplus_username:  113319261045405013233
disqus_username: erikjhordanreyes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Talks
    url: /series
  - title: Courses
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
