# Site
name: Erik Jhordan Rey
description: Just another website
meta_description: Just another website
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'erikjhordan.rey@gmail.com'
google_analytics:
disqus: xjekyll
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a1a46b37b0f3600122c23bc&product=sticky-share-buttons"></script>'

# Authors
authors:
  john:
    name: Erik Jhordan Rey
    display_name: Erik Jhordan Rey
    image: /assets/images/profile.jpg
    email: erikjhordan.rey@gmail.com
    web: example.com
    twitter:
    description: Hi, I am Erik Jhordan Rey.

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: ErikJhordan_Rey
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: ErikJhordan_Rey
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://plus.google.com/
    - https://github.com/
