# Site settings
title: ErikJhordan_Rey
description: A blog about Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erikcaffrey.github.io" # the base hostname & protocol for your site e.g.

# User settings
username: Erik Jhordan Rey
user_description: Android Software Engineer at Schibsted / Segundamano
user_title: Software Engineer
email: erik.gonzalez@schibsted.com
twitter_username: ErikJhordan_Rey
github_username:  erikcaffrey
gplus_username:  113319261045405013233
disqus_username: erikcaffreyblog

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Android
    url: /android
  - title: Software Development
    url: /software-development
  - title: Talks
    url: /talks
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
