# Site
name: Erik Jhordan Rey
description: Erik's Blog
meta_description: Erik's Blog
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'erikjhordan.rey@gmail.com'
google_analytics:
disqus: erikcaffrey-github-io

# Authors
authors:
  erik:
    name: Erik Jhordan Rey
    display_name: Erik Jhordan Rey
    image: /assets/images/profile.png
    email: erikjhordan.rey@gmail.com
    web:
    twitter: ErikJhordan_Rey
    description: Software Engineer at Segundamano · Adevinta

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: ErikJhordan_Rey
  card: summary

facebook:
  app_id:
  publisher: Erik Jhordan Rey
  admins:

social:
name: ErikJhordan_Rey
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://plus.google.com/
    - https://github.com/
